import { Crimes } from "../data/crimes";

const crimesTranslation = {
  [Crimes.THREAT]: "Ameaça verbal/física",
  [Crimes.LIBEL]: "Difamação/Calúnia",
  [Crimes.AGGRESSION]: "Lesão corporal (agressão)",
  [Crimes.PERJURY]: "Falso testemunho",
  [Crimes.CRIME_APOLOGY]: "Apologia ao crime",
  [Crimes.MASK]: "Ocultação de face (Máscara)",
  [Crimes.BULLETPROOF_VEST]: "Use de traje balístico (Polícia)",
  [Crimes.BRIBERY]: "Tentativa de suborno",
  [Crimes.HOUSE_INVASION]: "Invasão a propriedade",
  [Crimes.IDEOLOGICAL_FALSEHOOD]: "Falsidade ideológica",
  [Crimes.VEHICLE_THEFT]: "Furto a veículo",
  [Crimes.PRISON_RESISTANCE]: "Resistência a prisão",
  [Crimes.THEFTED_VEHICLE_RECEPTION]: "Receptação de veículo furtado",
  [Crimes.THEFT]: "Roubo",
  [Crimes.SHOP_THEFT]: "Assalto a lojas",
  [Crimes.AMMUNATION_THEFT]: "Assalto a ammunation",
  [Crimes.BANK_THEFT]: "Assalto a bancos",
  [Crimes.CASH_REGISTER_THEFT]: "Assalto a caixa registradora",
  [Crimes.DISACATO]: "Desacato",
  [Crimes.POLICE_ORDER_DISOBEDIENCE]: "Desobediência a ordem policial",
  [Crimes.KIDNAPPING]: "Sequestro ou tentativa",
  [Crimes.LEAVE_ATTEMPT]: "Tentativa de fuga",
  [Crimes.ACCOMPLICE]: "Cúmplice",
  [Crimes.EXTORSION]: "Extorção",
  [Crimes.GANG]: "Formação de quadrilha",
  [Crimes.PUBLIC_SHOOTING]: "Disparo de arma de fogo em público",
  [Crimes.MURDER_C]: "Homicídio culposo",
  [Crimes.MURDER_D]: "Homicídio doloso",
  [Crimes.ROBBERY]: "Latrocínio (Roubo seguido de morte)",
  [Crimes.MURDER_ATTEMPT]: "Tentativa de homicídio",
  [Crimes.TERRORISM]: "Terrorismo",
  [Crimes.LOW_GUN_PORT]: "Porte ilegal de baixo calibre",
  [Crimes.HIGH_GUN_PORT]: "Porte ilegal de alto calibre",
  [Crimes.ILICIT_PORT]: "Posse/porte de itens ilícitos",
  [Crimes.MARKED_MONEY]: "Dinheiro sujo/marcado",
  [Crimes.DRUG_SELLING]: "Tráfico de drogas (Acima de 3 unidades)",
  [Crimes.VEHICLE_ABANDONMENT]: "Abandono de veículo",
  [Crimes.DANGER_DRIVING]: "Direção perigosa",
  [Crimes.ILLEGAL_PARKING]: "Estacionar em local proibido",
  [Crimes.CLONNED_PLATE]: "Placa clonada",
  [Crimes.CRIME_WITH_SERVICE_CAR]: "Uso de carro de serviço em crimes",
  [Crimes.ILLEGAL_RACE]: "Prática de corrida ilegal",
  [Crimes.DESTRUCTED_VEHICLE]: "Veículo gravemente avariado",
  [Crimes.SPEED_EXCESS]: "Excesso de velocidade em lugares públicos",
  [Crimes.HELICOPTER_LANDING_AT_PUBLIC_PLACES]:
    "Pouso de helicóptero em local proibido",
};

export default function getCrimeName(name: Crimes) {
  return crimesTranslation[name];
}
